format = """
[╭─](bold blue)$directory
[╰─](bold blue)$character
"""
add_newline = true

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vicmd_symbol = "[❮](bold yellow)"

[directory]
style = "bold cyan"
truncate_to_repo = false
truncation_length = 3
